1. Data Understanding

In [1]:
#install library kaggle untuk mengakses dataset dari Kaggle
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.5.20)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)

In [2]:
import kagglehub
# Download latest version
path = kagglehub.dataset_download("mahdimashayekhi/disease-risk-from-daily-habits")
print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/mahdimashayekhi/disease-risk-from-daily-habits/1.archive...

100%|██████████| 20.8M/20.8M [00:02<00:00, 8.03MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/mahdimashayekhi/disease-risk-from-daily-habits/versions/1

In [3]:
#install library catboost untuk model machine learning
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.2 MB/s eta 0:00:000:00:0100:01
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [4]:
# Import library yang dibutuhkan
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.model_selection import GridSearchCV

In [5]:
# mengecek file yang telah di download
print(os.listdir(path))

['health_lifestyle_classification.csv']

In [6]:
# Membaca dataset
df = pd.read_csv(path + "/health_lifestyle_classification.csv")
df.head()

,survey_code,age,gender,height,weight,bmi,bmi_estimated,bmi_scaled,bmi_corrected,waist_size,...,sunlight_exposure,meals_per_day,caffeine_intake,family_history,pet_owner,electrolyte_level,gene_marker_flag,environmental_risk_score,daily_supplement_dosage,target
0,1,56,Male,173.416872,56.886640,18.915925,18.915925,56.747776,18.989117,72.165130,...,High,5,Moderate,No,Yes,0,1.0,5.5,-2.275502,healthy
1,2,69,Female,163.207380,97.799859,36.716278,36.716278,110.148833,36.511417,85.598889,...,High,5,High,Yes,No,0,1.0,5.5,6.239340,healthy
2,3,46,Male,177.281966,80.687562,25.673050,25.673050,77.019151,25.587429,90.295030,...,High,4,Moderate,No,No,0,1.0,5.5,5.423737,healthy
3,4,32,Female,172.101255,63.142868,21.318480,21.318480,63.955440,21.177109,100.504211,...,High,1,NaN,No,Yes,0,1.0,5.5,8.388611,healthy
4,5,60,Female,163.608816,40.000000,14.943302,14.943302,44.829907,14.844299,69.021150,...,High,1,High,Yes,Yes,0,1.0,5.5,0.332622,healthy

In [7]:
# mengecek jumlah baris dan kolom pada dataset
print("data shape : ", df.shape)

data shape :  (100000, 48)

In [8]:
# Mengecek informasi dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 48 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   survey_code               100000 non-null  int64
 1   age                       100000 non-null  int64
 2   gender                    100000 non-null  object
 3   height                    100000 non-null  float64
 4   weight                    100000 non-null  float64
 5   bmi                       100000 non-null  float64
 6   bmi_estimated             100000 non-null  float64
 7   bmi_scaled                100000 non-null  float64
 8   bmi_corrected             100000 non-null  float64
 9   waist_size                100000 non-null  float64
 10  blood_pressure            92331 non-null   float64
 11  heart_rate                85997 non-null   float64
 12  cholesterol               100000 non-null  float64
 13  glucose                   100000 non-null  float64
 14  insulin                   84164 non-null   float64
 15  sleep_hours               100000 non-null  float64
 16  sleep_quality             100000 non-null  object
 17  work_hours                100000 non-null  float64
 18  physical_activity         100000 non-null  float64
 19  daily_steps               91671 non-null   float64
 20  calorie_intake            100000 non-null  float64
 21  sugar_intake              100000 non-null  float64
 22  alcohol_consumption       57613 non-null   object
 23  smoking_level             100000 non-null  object
 24  water_intake              100000 non-null  float64
 25  screen_time               100000 non-null  float64
 26  stress_level              100000 non-null  int64
 27  mental_health_score       100000 non-null  int64
 28  mental_health_support     100000 non-null  object
 29  education_level           100000 non-null  object
 30  job_type                  100000 non-null  object
 31  occupation                100000 non-null  object
 32  income                    91530 non-null   float64
 33  diet_type                 100000 non-null  object
 34  exercise_type             75031 non-null   object
 35  device_usage              100000 non-null  object
 36  healthcare_access         100000 non-null  object
 37  insurance                 100000 non-null  object
 38  sunlight_exposure         100000 non-null  object
 39  meals_per_day             100000 non-null  int64
 40  caffeine_intake           66739 non-null   object
 41  family_history            100000 non-null  object
 42  pet_owner                 100000 non-null  object
 43  electrolyte_level         100000 non-null  int64
 44  gene_marker_flag          89526 non-null   float64
 45  environmental_risk_score  100000 non-null  float64
 46  daily_supplement_dosage   100000 non-null  float64
 47  target                    100000 non-null  object
dtypes: float64(24), int64(6), object(18)
memory usage: 36.6+ MB

In [9]:
# describe dataset untuk melihat statistik dasar dari dataset
df.describe()

,survey_code,age,height,weight,bmi,bmi_estimated,bmi_scaled,bmi_corrected,waist_size,blood_pressure,...,water_intake,screen_time,stress_level,mental_health_score,income,meals_per_day,electrolyte_level,gene_marker_flag,environmental_risk_score,daily_supplement_dosage
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,92331.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,91530.000000,100000.000000,100000.0,89526.0,100000.0,100000.000000
mean,50000.500000,48.525990,170.023707,70.064862,24.493876,24.493876,73.481627,24.494140,84.933043,119.980149,...,2.006373,6.021525,4.991600,5.004680,4038.127284,2.998720,0.0,1.0,5.5,0.015726
std,28867.657797,17.886768,9.982798,14.693667,5.951069,5.951069,17.853206,5.954184,12.040314,15.015503,...,0.688868,2.933835,3.154997,3.164228,1930.025678,1.414786,0.0,0.0,0.0,5.764489
min,1.000000,18.000000,140.000000,40.000000,9.988495,9.988495,29.965484,9.893845,34.093185,59.128168,...,0.500000,0.000000,0.000000,0.000000,500.000000,1.000000,0.0,1.0,5.5,-9.999895
25%,25000.750000,33.000000,163.306615,59.856938,20.271405,20.271405,60.814215,20.271059,76.795185,109.812060,...,1.532011,3.971318,2.000000,2.000000,2665.402843,2.000000,0.0,1.0,5.5,-4.980501
50%,50000.500000,48.000000,170.016778,69.924141,24.156734,24.156734,72.470201,24.151699,84.957139,119.951794,...,2.000659,5.991171,5.000000,5.000000,4004.601345,3.000000,0.0,1.0,5.5,0.015589
75%,75000.250000,64.000000,176.728920,80.027418,28.258696,28.258696,84.776088,28.247648,93.018713,130.120621,...,2.473047,8.024470,8.000000,8.000000,5360.012694,4.000000,0.0,1.0,5.5,5.008424
max,100000.000000,79.000000,210.000000,139.250894,59.234792,59.234792,177.704377,59.142646,133.153631,184.439195,...,5.000000,16.000000,10.000000,10.000000,12029.409353,5.000000,0.0,1.0,5.5,9.999966

2. Cleaning Data

# missing value

In [10]:
# Mengecek nilai yang hilang
missing_values = df.isnull().sum()

print("missing value per kolom : ")
print(missing_values[missing_values>0])

missing value per kolom :
blood_pressure          7669
heart_rate             14003
insulin                15836
daily_steps             8329
alcohol_consumption    42387
income                  8470
exercise_type          24969
caffeine_intake        33261
gene_marker_flag       10474
dtype: int64

In [11]:
# Mengecek persentase nilai yang hilang
missing_percentage = df.isnull().mean().sort_values(ascending=False)*100
print("percentage of missing values per column : ")
print(missing_percentage[missing_percentage>0])

percentage of missing values per column :
alcohol_consumption    42.387
caffeine_intake        33.261
exercise_type          24.969
insulin                15.836
heart_rate             14.003
gene_marker_flag       10.474
income                  8.470
daily_steps             8.329
blood_pressure          7.669
dtype: float64

In [12]:
# Mengecek jumlah nilai yang hilang per kolom
print("Jumlah Missing Value tiap kolom:\n")

print(df.isna().sum())

Jumlah Missing Value tiap kolom:

survey_code                     0
age                             0
gender                          0
height                          0
weight                          0
bmi                             0
bmi_estimated                   0
bmi_scaled                      0
bmi_corrected                   0
waist_size                      0
blood_pressure               7669
heart_rate                  14003
cholesterol                     0
glucose                         0
insulin                     15836
sleep_hours                     0
sleep_quality                   0
work_hours                      0
physical_activity               0
daily_steps                  8329
calorie_intake                  0
sugar_intake                    0
alcohol_consumption         42387
smoking_level                   0
water_intake                    0
screen_time                     0
stress_level                    0
mental_health_score             0
mental_health_support           0
education_level                 0
job_type                        0
occupation                      0
income                       8470
diet_type                       0
exercise_type               24969
device_usage                    0
healthcare_access               0
insurance                       0
sunlight_exposure               0
meals_per_day                   0
caffeine_intake             33261
family_history                  0
pet_owner                       0
electrolyte_level               0
gene_marker_flag            10474
environmental_risk_score        0
daily_supplement_dosage         0
target                          0
dtype: int64

In [13]:
# Mengecek jumlah nilai yang hilang secara keseluruhan dataset
df.isna().sum().sum()

np.int64(165398)

In [14]:
# Mengisi nilai yang hilang dengan median untuk kolom numerik dan modus untuk kolom kategorikal

# 1) Kolom numerik
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
for col in num_cols:
    df[col] = df[col].fillna(
        df[col].median()
    )

# 2) Kolom kategorikal
cat_cols = df.select_dtypes(
    include='object'
).columns

for col in cat_cols:
    df[col] = df[col].fillna(
        "Unknown"
    )

In [15]:
(df.isna().sum()/len(df))*100

survey_code                 0.0
age                         0.0
gender                      0.0
height                      0.0
weight                      0.0
bmi                         0.0
bmi_estimated               0.0
bmi_scaled                  0.0
bmi_corrected               0.0
waist_size                  0.0
blood_pressure              0.0
heart_rate                  0.0
cholesterol                 0.0
glucose                     0.0
insulin                     0.0
sleep_hours                 0.0
sleep_quality               0.0
work_hours                  0.0
physical_activity           0.0
daily_steps                 0.0
calorie_intake              0.0
sugar_intake                0.0
alcohol_consumption         0.0
smoking_level               0.0
water_intake                0.0
screen_time                 0.0
stress_level                0.0
mental_health_score         0.0
mental_health_support       0.0
education_level             0.0
job_type                    0.0
occupation                  0.0
income                      0.0
diet_type                   0.0
exercise_type               0.0
device_usage                0.0
healthcare_access           0.0
insurance                   0.0
sunlight_exposure           0.0
meals_per_day               0.0
caffeine_intake             0.0
family_history              0.0
pet_owner                   0.0
electrolyte_level           0.0
gene_marker_flag            0.0
environmental_risk_score    0.0
daily_supplement_dosage     0.0
target                      0.0
dtype: float64

In [16]:
df.isna().sum().sum()

np.int64(0)

In [17]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 48 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   survey_code               100000 non-null  int64
 1   age                       100000 non-null  int64
 2   gender                    100000 non-null  object
 3   height                    100000 non-null  float64
 4   weight                    100000 non-null  float64
 5   bmi                       100000 non-null  float64
 6   bmi_estimated             100000 non-null  float64
 7   bmi_scaled                100000 non-null  float64
 8   bmi_corrected             100000 non-null  float64
 9   waist_size                100000 non-null  float64
 10  blood_pressure            100000 non-null  float64
 11  heart_rate                100000 non-null  float64
 12  cholesterol               100000 non-null  float64
 13  glucose                   100000 non-null  float64
 14  insulin                   100000 non-null  float64
 15  sleep_hours               100000 non-null  float64
 16  sleep_quality             100000 non-null  object
 17  work_hours                100000 non-null  float64
 18  physical_activity         100000 non-null  float64
 19  daily_steps               100000 non-null  float64
 20  calorie_intake            100000 non-null  float64
 21  sugar_intake              100000 non-null  float64
 22  alcohol_consumption       100000 non-null  object
 23  smoking_level             100000 non-null  object
 24  water_intake              100000 non-null  float64
 25  screen_time               100000 non-null  float64
 26  stress_level              100000 non-null  int64
 27  mental_health_score       100000 non-null  int64
 28  mental_health_support     100000 non-null  object
 29  education_level           100000 non-null  object
 30  job_type                  100000 non-null  object
 31  occupation                100000 non-null  object
 32  income                    100000 non-null  float64
 33  diet_type                 100000 non-null  object
 34  exercise_type             100000 non-null  object
 35  device_usage              100000 non-null  object
 36  healthcare_access         100000 non-null  object
 37  insurance                 100000 non-null  object
 38  sunlight_exposure         100000 non-null  object
 39  meals_per_day             100000 non-null  int64
 40  caffeine_intake           100000 non-null  object
 41  family_history            100000 non-null  object
 42  pet_owner                 100000 non-null  object
 43  electrolyte_level         100000 non-null  int64
 44  gene_marker_flag          100000 non-null  float64
 45  environmental_risk_score  100000 non-null  float64
 46  daily_supplement_dosage   100000 non-null  float64
 47  target                    100000 non-null  object
dtypes: float64(24), int64(6), object(18)
memory usage: 36.6+ MB
None

# cek duplikat

In [18]:
# Mengecek duplikasi data
df.duplicated().sum()

np.int64(0)

In [19]:
df[df.duplicated()]

Empty DataFrame
Columns: [survey_code, age, gender, height, weight, bmi, bmi_estimated, bmi_scaled, bmi_corrected, waist_size, blood_pressure, heart_rate, cholesterol, glucose, insulin, sleep_hours, sleep_quality, work_hours, physical_activity, daily_steps, calorie_intake, sugar_intake, alcohol_consumption, smoking_level, water_intake, screen_time, stress_level, mental_health_score, mental_health_support, education_level, job_type, occupation, income, diet_type, exercise_type, device_usage, healthcare_access, insurance, sunlight_exposure, meals_per_day, caffeine_intake, family_history, pet_owner, electrolyte_level, gene_marker_flag, environmental_risk_score, daily_supplement_dosage, target]
Index: []

[0 rows x 48 columns]

In [20]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [survey_code, age, gender, height, weight, bmi, bmi_estimated, bmi_scaled, bmi_corrected, waist_size, blood_pressure, heart_rate, cholesterol, glucose, insulin, sleep_hours, sleep_quality, work_hours, physical_activity, daily_steps, calorie_intake, sugar_intake, alcohol_consumption, smoking_level, water_intake, screen_time, stress_level, mental_health_score, mental_health_support, education_level, job_type, occupation, income, diet_type, exercise_type, device_usage, healthcare_access, insurance, sunlight_exposure, meals_per_day, caffeine_intake, family_history, pet_owner, electrolyte_level, gene_marker_flag, environmental_risk_score, daily_supplement_dosage, target]
Index: []

[0 rows x 48 columns]

In [21]:
# ============================================================
# CEK DUPLICATE DATA
# ============================================================

# Total duplicate
total_duplicate = df.duplicated().sum()

print("Total Duplicate:", total_duplicate)

# Persentase duplicate
duplicate_percent = (
    total_duplicate / len(df)
) * 100

print(
    "Persentase Duplicate:",
    round(duplicate_percent, 2),
    "%"
)

# ============================================================
# TAMPILKAN DATA DUPLICATE
# ============================================================

duplicate_rows = df[
    df.duplicated(keep=False)
]

print("\nData Duplicate:\n")

print(duplicate_rows)

# ============================================================
# JUMLAH ROW DUPLICATE
# ============================================================

print(
    "\nJumlah Row Duplicate:",
    duplicate_rows.shape[0]
)

Total Duplicate: 0
Persentase Duplicate: 0.0 %

Data Duplicate:

Empty DataFrame
Columns: [survey_code, age, gender, height, weight, bmi, bmi_estimated, bmi_scaled, bmi_corrected, waist_size, blood_pressure, heart_rate, cholesterol, glucose, insulin, sleep_hours, sleep_quality, work_hours, physical_activity, daily_steps, calorie_intake, sugar_intake, alcohol_consumption, smoking_level, water_intake, screen_time, stress_level, mental_health_score, mental_health_support, education_level, job_type, occupation, income, diet_type, exercise_type, device_usage, healthcare_access, insurance, sunlight_exposure, meals_per_day, caffeine_intake, family_history, pet_owner, electrolyte_level, gene_marker_flag, environmental_risk_score, daily_supplement_dosage, target]
Index: []

[0 rows x 48 columns]

Jumlah Row Duplicate: 0

In [22]:
df.head()

,survey_code,age,gender,height,weight,bmi,bmi_estimated,bmi_scaled,bmi_corrected,waist_size,...,sunlight_exposure,meals_per_day,caffeine_intake,family_history,pet_owner,electrolyte_level,gene_marker_flag,environmental_risk_score,daily_supplement_dosage,target
0,1,56,Male,173.416872,56.886640,18.915925,18.915925,56.747776,18.989117,72.165130,...,High,5,Moderate,No,Yes,0,1.0,5.5,-2.275502,healthy
1,2,69,Female,163.207380,97.799859,36.716278,36.716278,110.148833,36.511417,85.598889,...,High,5,High,Yes,No,0,1.0,5.5,6.239340,healthy
2,3,46,Male,177.281966,80.687562,25.673050,25.673050,77.019151,25.587429,90.295030,...,High,4,Moderate,No,No,0,1.0,5.5,5.423737,healthy
3,4,32,Female,172.101255,63.142868,21.318480,21.318480,63.955440,21.177109,100.504211,...,High,1,Unknown,No,Yes,0,1.0,5.5,8.388611,healthy
4,5,60,Female,163.608816,40.000000,14.943302,14.943302,44.829907,14.844299,69.021150,...,High,1,High,Yes,Yes,0,1.0,5.5,0.332622,healthy

3. Cek Tipe Data

In [23]:
# Mengecek tipe data setiap kolom
print(df.dtypes)

survey_code                   int64
age                           int64
gender                       object
height                      float64
weight                      float64
bmi                         float64
bmi_estimated               float64
bmi_scaled                  float64
bmi_corrected               float64
waist_size                  float64
blood_pressure              float64
heart_rate                  float64
cholesterol                 float64
glucose                     float64
insulin                     float64
sleep_hours                 float64
sleep_quality                object
work_hours                  float64
physical_activity           float64
daily_steps                 float64
calorie_intake              float64
sugar_intake                float64
alcohol_consumption          object
smoking_level                object
water_intake                float64
screen_time                 float64
stress_level                  int64
mental_health_score           int64
mental_health_support        object
education_level              object
job_type                     object
occupation                   object
income                      float64
diet_type                    object
exercise_type                object
device_usage                 object
healthcare_access            object
insurance                    object
sunlight_exposure            object
meals_per_day                 int64
caffeine_intake              object
family_history               object
pet_owner                    object
electrolyte_level             int64
gene_marker_flag            float64
environmental_risk_score    float64
daily_supplement_dosage     float64
target                       object
dtype: object

In [24]:
# Mengecek nilai unik pada setiap kolom kategorikal
for col in df.select_dtypes(include='object'):

    print(f"\n===== {col} =====")

    print(df[col].unique())

===== gender =====
['Male' 'Female']

===== sleep_quality =====
['Fair' 'Good' 'Poor' 'Excellent']

===== alcohol_consumption =====
['Unknown' 'Regularly' 'Occasionally']

===== smoking_level =====
['Non-smoker' 'Light' 'Heavy']

===== mental_health_support =====
['No' 'Yes']

===== education_level =====
['PhD' 'High School' 'Master' 'Bachelor']

===== job_type =====
['Tech' 'Office' 'Labor' 'Unemployed' 'Service' 'Healthcare']

===== occupation =====
['Farmer' 'Engineer' 'Teacher' 'Doctor' 'Driver' 'Artist']

===== diet_type =====
['Vegan' 'Vegetarian' 'Omnivore' 'Keto']

===== exercise_type =====
['Strength' 'Cardio' 'Mixed' 'Unknown']

===== device_usage =====
['High' 'Moderate' 'Low']

===== healthcare_access =====
['Poor' 'Moderate' 'Good']

===== insurance =====
['No' 'Yes']

===== sunlight_exposure =====
['High' 'Low' 'Moderate']

===== caffeine_intake =====
['Moderate' 'High' 'Unknown']

===== family_history =====
['No' 'Yes']

===== pet_owner =====
['Yes' 'No']

===== target =====
['healthy' 'diseased']

In [25]:
# mengecek semua isi tabel untuk memastikan tidak ada nilai yang aneh atau tidak konsisten

# Tampilkan semua kolom
pd.set_option('display.max_columns', None)

# Lebar tampilan terminal
pd.set_option('display.width', 1000)

# Panjang isi kolom tidak dipotong
pd.set_option('display.max_colwidth', None)

# Tampilkan semua baris jika diperlukan
pd.set_option('display.max_rows', None)

In [26]:
df.head()

   survey_code  age  gender      height     weight        bmi  bmi_estimated  bmi_scaled  bmi_corrected  waist_size  blood_pressure  heart_rate  cholesterol     glucose    insulin  sleep_hours sleep_quality  work_hours  physical_activity   daily_steps  calorie_intake  sugar_intake alcohol_consumption smoking_level  water_intake  screen_time  stress_level  mental_health_score mental_health_support education_level    job_type occupation       income   diet_type exercise_type device_usage healthcare_access insurance sunlight_exposure  meals_per_day caffeine_intake family_history pet_owner  electrolyte_level  gene_marker_flag  environmental_risk_score  daily_supplement_dosage   target
0            1   56    Male  173.416872  56.886640  18.915925      18.915925   56.747776      18.989117   72.165130      118.264254   60.749825   214.580523  103.008176  14.983414     6.475885          Fair    7.671313           0.356918  13320.942595     2673.546960     44.476887             Unknown    Non-smoker      1.694262     5.003963             2                    8                    No             PhD        Tech     Farmer  6759.821719       Vegan      Strength         High              Poor        No              High              5        Moderate             No       Yes                  0               1.0                       5.5                -2.275502  healthy
1            2   69  Female  163.207380  97.799859  36.716278      36.716278  110.148833      36.511417   85.598889      117.917986   66.463696   115.794002  116.905134  10.131597     8.428410          Good    9.515198           0.568219  11911.201401     2650.376972     74.663405           Regularly         Light      0.716409     5.925455             3                    9                    No     High School      Office   Engineer  6240.517690       Vegan        Cardio     Moderate          Moderate        No              High              5            High            Yes        No                  0               1.0                       5.5                 6.239340  healthy
2            3   46    Male  177.281966  80.687562  25.673050      25.673050   77.019151      25.587429   90.295030      123.073698   76.043212   138.134787   89.180302  14.983414     5.702164          Poor    5.829853           3.764406   2974.035375     1746.755144     19.702382           Regularly         Heavy      2.487900     4.371250             0                    1                    No          Master      Office    Teacher  3429.179266       Vegan        Cardio         High              Good       Yes              High              4        Moderate             No        No                  0               1.0                       5.5                 5.423737  healthy
3            4   32  Female  172.101255  63.142868  21.318480      21.318480   63.955440      21.177109  100.504211      148.173453   68.781981   203.017447  128.375798  18.733179     5.188316          Good    9.489693           0.889474   5321.539497     2034.193242     82.580050        Occasionally         Heavy      2.643335     4.116064            10                    4                    No          Master       Labor    Teacher  2618.503534  Vegetarian         Mixed          Low          Moderate        No              High              1         Unknown             No       Yes                  0               1.0                       5.5                 8.388611  healthy
4            5   60  Female  163.608816  40.000000  14.943302      14.943302   44.829907      14.844299   69.021150      150.613181   92.335358   200.412439   94.813332  16.038701     7.912514          Good    7.275450           2.901608   9791.376712     2386.210257     45.961322             Unknown         Heavy      1.968393     3.180087             9                    7                   Yes          Master  Unemployed     Doctor  3662.086276       Vegan       Unknown          Low          Moderate       Yes              High              1            High            Yes       Yes                  0               1.0                       5.5                 0.332622  healthy

In [27]:
cat_cols = [
    'gender',
    'diet_type',
    'exercise_type',
    'smoking_level'
]

for col in cat_cols:
    df[col] = df[col].astype(str)



for col in cat_cols:
    print(col)
    print(df[col].unique())
    print("="*50)

gender
['Male' 'Female']
==================================================
diet_type
['Vegan' 'Vegetarian' 'Omnivore' 'Keto']
==================================================
exercise_type
['Strength' 'Cardio' 'Mixed' 'Unknown']
==================================================
smoking_level
['Non-smoker' 'Light' 'Heavy']
==================================================

In [28]:
df.describe()

         survey_code            age         height         weight            bmi  bmi_estimated     bmi_scaled  bmi_corrected     waist_size  blood_pressure     heart_rate    cholesterol        glucose        insulin    sleep_hours     work_hours  physical_activity    daily_steps  calorie_intake   sugar_intake   water_intake    screen_time   stress_level  mental_health_score         income  meals_per_day  electrolyte_level  gene_marker_flag  environmental_risk_score  daily_supplement_dosage
count  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000   100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000      100000.000000  100000.000000   100000.000000  100000.000000  100000.000000  100000.000000  100000.000000        100000.000000  100000.000000  100000.000000           100000.0          100000.0                  100000.0            100000.000000
mean    50000.500000      48.525990     170.023707      70.064862      24.493876      24.493876      73.481627      24.494140      84.933043      119.977974      74.979964     189.966438      99.994538      14.987491       7.002008       8.001331           3.038344    7012.206098     2201.428579      60.047165       2.006373       6.021525       4.991600             5.004680    4035.287636       2.998720                0.0               1.0                       5.5                 0.015726
std     28867.657797      17.886768       9.982798      14.693667       5.951069       5.951069      17.853206       5.954184      12.040314       14.428246       9.219394      29.981934      19.982828       4.589596       1.496821       1.994723           1.884475    2383.082319      400.516318      19.966850       0.688868       2.933835       3.154997             3.164228    1846.503636       1.414786                0.0               0.0                       0.0                 5.764489
min         1.000000      18.000000     140.000000      40.000000       9.988495       9.988495      29.965484       9.893845      34.093185       59.128168      34.745092      58.410902      12.434931      -6.794483       3.000000       0.000000           0.000000    1000.000000      527.172360     -27.882444       0.500000       0.000000       0.000000             0.000000     500.000000       1.000000                0.0               1.0                       5.5                -9.999895
25%     25000.750000      33.000000     163.306615      59.856938      20.271405      20.271405      60.814215      20.271059      76.795185      110.815119      69.543894     169.667738      86.461401      12.324714       5.986781       6.651093           1.633799    5500.327842     1932.278165      46.504292       1.532011       3.971318       2.000000             2.000000    2796.061969       2.000000                0.0               1.0                       5.5                -4.980501
50%     50000.500000      48.000000     170.016778      69.924141      24.156734      24.156734      72.470201      24.151699      84.957139      119.951794      75.046211     190.044579      99.986834      14.983414       6.998164       8.004549           2.971222    7004.285450     2200.992765      60.047905       2.000659       5.991171       5.000000             5.000000    4004.601345       3.000000                0.0               1.0                       5.5                 0.015589
75%     75000.250000      64.000000     176.728920      80.027418      28.258696      28.258696      84.776088      28.247648      93.018713      129.185145      80.467128     210.222005     113.508722      17.663430       8.019219       9.353669           4.326500    8523.819577     2471.218160      73.476386       2.473047       8.024470       8.000000             8.000000    5219.230324       4.000000                0.0               1.0                       5.5                 5.008424
max    100000.000000      79.000000     210.000000     139.250894      59.234792      59.234792     177.704377      59.142646     133.153631      184.439195     114.136041     319.875613     183.883548      35.464749      12.000000      16.000000          11.631898   18064.969543     3949.019017     141.514522       5.000000      16.000000      10.000000            10.000000   12029.409353       5.000000                0.0               1.0                       5.5                 9.999966

In [29]:
print(df['target'].value_counts())
 
print(df['target'].value_counts(normalize=True))

target
healthy     70097
diseased    29903
Name: count, dtype: int64
target
healthy     0.70097
diseased    0.29903
Name: proportion, dtype: float64

In [30]:
# Menghapus kolom yang tidak diperlukan 
df = df.drop(columns=[
'survey_code',
'bmi_estimated','bmi_scaled','bmi_corrected',
'mental_health_score','mental_health_support',
'education_level','job_type','occupation',
'income','healthcare_access','insurance',
'sunlight_exposure','family_history','pet_owner',
'electrolyte_level','gene_marker_flag',
'environmental_risk_score','daily_supplement_dosage'
])

In [31]:
# Mengubah tipe data category menjadi string 
category_cols = df.select_dtypes(include='category').columns

for col in category_cols:
    df[col] = df[col].astype(str)

In [32]:
# Encode target
df['target'] = df['target'].map({
    'healthy': 0,
    'diseased': 1
})

Encoding Kategorikal

In [33]:
X = df.drop('target', axis=1)
y = df['target']

# Ambil semua kolom kategorikal (object)
cat_features = X.select_dtypes(include=['object', 'category']).columns.tolist()

In [34]:
df.head()

   age  gender      height     weight        bmi  waist_size  blood_pressure  heart_rate  cholesterol     glucose    insulin  sleep_hours sleep_quality  work_hours  physical_activity   daily_steps  calorie_intake  sugar_intake alcohol_consumption smoking_level  water_intake  screen_time  stress_level   diet_type exercise_type device_usage  meals_per_day caffeine_intake  target
0   56    Male  173.416872  56.886640  18.915925   72.165130      118.264254   60.749825   214.580523  103.008176  14.983414     6.475885          Fair    7.671313           0.356918  13320.942595     2673.546960     44.476887             Unknown    Non-smoker      1.694262     5.003963             2       Vegan      Strength         High              5        Moderate       0
1   69  Female  163.207380  97.799859  36.716278   85.598889      117.917986   66.463696   115.794002  116.905134  10.131597     8.428410          Good    9.515198           0.568219  11911.201401     2650.376972     74.663405           Regularly         Light      0.716409     5.925455             3       Vegan        Cardio     Moderate              5            High       0
2   46    Male  177.281966  80.687562  25.673050   90.295030      123.073698   76.043212   138.134787   89.180302  14.983414     5.702164          Poor    5.829853           3.764406   2974.035375     1746.755144     19.702382           Regularly         Heavy      2.487900     4.371250             0       Vegan        Cardio         High              4        Moderate       0
3   32  Female  172.101255  63.142868  21.318480  100.504211      148.173453   68.781981   203.017447  128.375798  18.733179     5.188316          Good    9.489693           0.889474   5321.539497     2034.193242     82.580050        Occasionally         Heavy      2.643335     4.116064            10  Vegetarian         Mixed          Low              1         Unknown       0
4   60  Female  163.608816  40.000000  14.943302   69.021150      150.613181   92.335358   200.412439   94.813332  16.038701     7.912514          Good    7.275450           2.901608   9791.376712     2386.210257     45.961322             Unknown         Heavy      1.968393     3.180087             9       Vegan       Unknown          Low              1            High       0

In [35]:
df['target'].value_counts()

target
0    70097
1    29903
Name: count, dtype: int64

In [36]:
# ============================================================
# SPLIT DATA
# ============================================================

from sklearn.model_selection import train_test_split

X = df.drop('target', axis=1)
y = df['target']

x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [37]:
# Mengecek data sebelum split
print(x_train.shape)

(80000, 28)

Mengatasi Imbalanced Data

In [38]:
# ============================================================
# INSTALL
# ============================================================

!pip install imbalanced-learn

# ============================================================
# IMPORT
# ============================================================

from imblearn.over_sampling import RandomOverSampler

# ============================================================
# CEK DISTRIBUSI SEBELUM
# ============================================================

print("Distribusi target sebelum Oversampling:\n")

print(y_train.value_counts())

# ============================================================
# OVERSAMPLING
# ============================================================

oversample = RandomOverSampler(
    sampling_strategy='auto',
    random_state=42
)

x_train_over, y_train_over = oversample.fit_resample(
    x_train,
    y_train
)

# ============================================================
# CEK DISTRIBUSI SETELAH
# ============================================================

print("\nDistribusi target setelah Oversampling:\n")

print(y_train_over.value_counts())

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.12/dist-packages (0.14.2)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (2.0.2)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (0.1.6)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (3.6.0)
Distribusi target sebelum Oversampling:

target
0    56078
1    23922
Name: count, dtype: int64

Distribusi target setelah Oversampling:

target
1    56078
0    56078
Name: count, dtype: int64

In [39]:
# Mengecek data setelah oversampling
print(x_train_over.shape)

(112156, 28)

In [40]:
print(x_train_over.dtypes)

age                      int64
gender                  object
height                 float64
weight                 float64
bmi                    float64
waist_size             float64
blood_pressure         float64
heart_rate             float64
cholesterol            float64
glucose                float64
insulin                float64
sleep_hours            float64
sleep_quality           object
work_hours             float64
physical_activity      float64
daily_steps            float64
calorie_intake         float64
sugar_intake           float64
alcohol_consumption     object
smoking_level           object
water_intake           float64
screen_time            float64
stress_level             int64
diet_type               object
exercise_type           object
device_usage            object
meals_per_day            int64
caffeine_intake         object
dtype: object

In [41]:
print(
    x_train_over.select_dtypes(
        include=['object','category']
    ).columns
)

Index(['gender', 'sleep_quality', 'alcohol_consumption', 'smoking_level', 'diet_type', 'exercise_type', 'device_usage', 'caffeine_intake'], dtype='object')

In [42]:
# ============================================================
# MODEL DASAR
# ============================================================

cat_model = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.03,
    depth=6,
    l2_leaf_reg=10,
    random_strength=5,
    bagging_temperature=1,
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=100,
    cat_features=cat_features
)

# ============================================================
# PARAMETER YANG DITUNING
# ============================================================

param_grid = {
    'depth': [5, 6],
    'learning_rate': [0.02, 0.03],
    'l2_leaf_reg': [10, 15],
    'random_strength': [5, 10],
    'bagging_temperature': [1, 3],
    'iterations': [1000]
}
# ============================================================
# GRID SEARCH
# ============================================================

grid_result = cat_model.grid_search(
    param_grid=param_grid,
    X=x_train_over,
    y=y_train_over,
    cv=3,
    partition_random_seed=42,
    verbose=True
)

# ============================================================
# PARAMETER TERBAIK
# ============================================================

print("Best Parameters:")
print(grid_result['params'])

0:	learn: 0.5620988	test: 0.5596737	best: 0.5596737 (0)	total: 213ms	remaining: 3m 32s
100:	learn: 0.5399076	test: 0.5206881	best: 0.5596737 (0)	total: 12.9s	remaining: 1m 54s
200:	learn: 0.5422477	test: 0.5196578	best: 0.5596737 (0)	total: 24.9s	remaining: 1m 39s
300:	learn: 0.5397453	test: 0.5156173	best: 0.5596737 (0)	total: 36.4s	remaining: 1m 24s
400:	learn: 0.5418178	test: 0.5166644	best: 0.5596737 (0)	total: 47.7s	remaining: 1m 11s
500:	learn: 0.5430517	test: 0.5173946	best: 0.5596737 (0)	total: 59.2s	remaining: 59s
600:	learn: 0.5490615	test: 0.5205247	best: 0.5596737 (0)	total: 1m 11s	remaining: 47.4s
700:	learn: 0.5717395	test: 0.5282968	best: 0.5596737 (0)	total: 1m 27s	remaining: 37.5s
800:	learn: 0.5955064	test: 0.5404229	best: 0.5596737 (0)	total: 1m 45s	remaining: 26.2s
900:	learn: 0.6102779	test: 0.5453175	best: 0.5596737 (0)	total: 2m 3s	remaining: 13.6s
999:	learn: 0.6226781	test: 0.5509109	best: 0.5596737 (0)	total: 2m 21s	remaining: 0us

bestTest = 0.5596737151
bestIteration = 0

0:	loss: 0.5596737	best: 0.5596737 (0)	total: 2m 21s	remaining: 1h 13m 7s
0:	learn: 0.5620988	test: 0.5596737	best: 0.5596737 (0)	total: 158ms	remaining: 2m 37s
100:	learn: 0.5303844	test: 0.5128321	best: 0.5596737 (0)	total: 11.8s	remaining: 1m 44s
200:	learn: 0.5310928	test: 0.5067234	best: 0.5596737 (0)	total: 23.6s	remaining: 1m 33s
300:	learn: 0.5339608	test: 0.5083948	best: 0.5596737 (0)	total: 35.1s	remaining: 1m 21s
400:	learn: 0.5418875	test: 0.5151338	best: 0.5596737 (0)	total: 48.1s	remaining: 1m 11s
500:	learn: 0.5791465	test: 0.5315034	best: 0.5596737 (0)	total: 1m 4s	remaining: 1m 4s
600:	learn: 0.6063014	test: 0.5465220	best: 0.5596737 (0)	total: 1m 23s	remaining: 55.5s
700:	learn: 0.6275468	test: 0.5542575	best: 0.5596737 (0)	total: 1m 41s	remaining: 43.1s
800:	learn: 0.6417767	test: 0.5618177	best: 0.5622811 (796)	total: 1m 59s	remaining: 29.6s
900:	learn: 0.6498802	test: 0.5662726	best: 0.5671151 (873)	total: 2m 17s	remaining: 15.1s
999:	learn: 0.6586402	test: 0.5707176	best: 0.5709839 (994)	total: 2m 35s	remaining: 0us

bestTest = 0.5709839491
bestIteration = 994

1:	loss: 0.5709839	best: 0.5709839 (1)	total: 4m 56s	remaining: 1h 14m 13s
0:	learn: 0.5620988	test: 0.5596737	best: 0.5596737 (0)	total: 163ms	remaining: 2m 42s
100:	learn: 0.5349881	test: 0.5182379	best: 0.5601108 (1)	total: 11.9s	remaining: 1m 45s
200:	learn: 0.5357127	test: 0.5176648	best: 0.5601108 (1)	total: 23.4s	remaining: 1m 33s
300:	learn: 0.5367304	test: 0.5188117	best: 0.5601108 (1)	total: 35s	remaining: 1m 21s
400:	learn: 0.5367614	test: 0.5190540	best: 0.5601108 (1)	total: 46.6s	remaining: 1m 9s
500:	learn: 0.5431928	test: 0.5198934	best: 0.5601108 (1)	total: 58s	remaining: 57.8s
600:	learn: 0.5496889	test: 0.5246032	best: 0.5601108 (1)	total: 1m 10s	remaining: 46.6s
700:	learn: 0.5712192	test: 0.5298002	best: 0.5601108 (1)	total: 1m 26s	remaining: 36.8s
800:	learn: 0.5965624	test: 0.5420428	best: 0.5601108 (1)	total: 1m 44s	remaining: 26.1s
900:	learn: 0.6141229	test: 0.5528670	best: 0.5601108 (1)	total: 2m 2s	remaining: 13.5s
999:	learn: 0.6244858	test: 0.5561601	best: 0.5601108 (1)	total: 2m 20s	remaining: 0us

bestTest = 0.5601108033
bestIteration = 1

2:	loss: 0.5601108	best: 0.5709839 (1)	total: 7m 17s	remaining: 1h 10m 24s
0:	learn: 0.5620988	test: 0.5596737	best: 0.5596737 (0)	total: 163ms	remaining: 2m 43s
100:	learn: 0.5387378	test: 0.5276644	best: 0.5601108 (1)	total: 12.3s	remaining: 1m 49s
200:	learn: 0.5400350	test: 0.5214001	best: 0.5601108 (1)	total: 24.1s	remaining: 1m 35s
300:	learn: 0.5407373	test: 0.5211889	best: 0.5601108 (1)	total: 35.9s	remaining: 1m 23s
400:	learn: 0.5477604	test: 0.5224512	best: 0.5601108 (1)	total: 47.5s	remaining: 1m 10s
500:	learn: 0.5838168	test: 0.5387346	best: 0.5601108 (1)	total: 1m 4s	remaining: 1m 4s
600:	learn: 0.6079206	test: 0.5495892	best: 0.5601108 (1)	total: 1m 23s	remaining: 55.3s
700:	learn: 0.6235841	test: 0.5527558	best: 0.5601108 (1)	total: 1m 40s	remaining: 43s
800:	learn: 0.6380834	test: 0.5597479	best: 0.5609334 (793)	total: 1m 59s	remaining: 29.7s
900:	learn: 0.6482101	test: 0.5650940	best: 0.5650940 (900)	total: 2m 16s	remaining: 15s
999:	learn: 0.6571207	test: 0.5675664	best: 0.5682303 (969)	total: 2m 34s	remaining: 0us

bestTest = 0.5682302772
bestIteration = 969

3:	loss: 0.5682303	best: 0.5709839 (1)	total: 9m 51s	remaining: 1h 9m 1s
0:	learn: 0.5087635	test: 0.5108648	best: 0.5108648 (0)	total: 120ms	remaining: 2m
100:	learn: 0.5234427	test: 0.5110148	best: 0.5680543 (2)	total: 11.7s	remaining: 1m 44s
200:	learn: 0.5276673	test: 0.5147998	best: 0.5680543 (2)	total: 23.3s	remaining: 1m 32s
300:	learn: 0.5278737	test: 0.5121556	best: 0.5680543 (2)	total: 33.7s	remaining: 1m 18s
400:	learn: 0.5294072	test: 0.5107920	best: 0.5680543 (2)	total: 44s	remaining: 1m 5s
500:	learn: 0.5305803	test: 0.5105577	best: 0.5680543 (2)	total: 54.5s	remaining: 54.3s
600:	learn: 0.5355953	test: 0.5157148	best: 0.5680543 (2)	total: 1m 5s	remaining: 43.5s
700:	learn: 0.5561817	test: 0.5253403	best: 0.5680543 (2)	total: 1m 20s	remaining: 34.5s
800:	learn: 0.5851898	test: 0.5373637	best: 0.5680543 (2)	total: 1m 38s	remaining: 24.4s
900:	learn: 0.6065386	test: 0.5483443	best: 0.5680543 (2)	total: 1m 56s	remaining: 12.8s
999:	learn: 0.6204738	test: 0.5552162	best: 0.5680543 (2)	total: 2m 14s	remaining: 0us

bestTest = 0.5680543022
bestIteration = 2

4:	loss: 0.5680543	best: 0.5709839 (1)	total: 12m 5s	remaining: 1h 5m 18s
0:	learn: 0.5087635	test: 0.5108648	best: 0.5108648 (0)	total: 76.2ms	remaining: 1m 16s
100:	learn: 0.5296574	test: 0.5126996	best: 0.5680543 (2)	total: 12.3s	remaining: 1m 49s
200:	learn: 0.5312969	test: 0.5170632	best: 0.5680543 (2)	total: 23.3s	remaining: 1m 32s
300:	learn: 0.5344944	test: 0.5199947	best: 0.5680543 (2)	total: 33.9s	remaining: 1m 18s
400:	learn: 0.5368738	test: 0.5182348	best: 0.5680543 (2)	total: 44.8s	remaining: 1m 6s
500:	learn: 0.5728550	test: 0.5352113	best: 0.5680543 (2)	total: 1m 1s	remaining: 1m 1s
600:	learn: 0.6015335	test: 0.5488722	best: 0.5680543 (2)	total: 1m 18s	remaining: 52.4s
700:	learn: 0.6202748	test: 0.5534329	best: 0.5680543 (2)	total: 1m 37s	remaining: 41.6s
800:	learn: 0.6329440	test: 0.5595270	best: 0.5680543 (2)	total: 1m 55s	remaining: 28.6s
900:	learn: 0.6454453	test: 0.5630446	best: 0.5680543 (2)	total: 2m 12s	remaining: 14.6s
999:	learn: 0.6560198	test: 0.5727708	best: 0.5729097 (998)	total: 2m 31s	remaining: 0us

bestTest = 0.5729097435
bestIteration = 998

5:	loss: 0.5729097	best: 0.5729097 (5)	total: 14m 37s	remaining: 1h 3m 23s
0:	learn: 0.5087635	test: 0.5108648	best: 0.5108648 (0)	total: 82.1ms	remaining: 1m 22s
100:	learn: 0.5318719	test: 0.5187398	best: 0.5245045 (67)	total: 11.5s	remaining: 1m 42s
200:	learn: 0.5342181	test: 0.5140431	best: 0.5245045 (67)	total: 22.7s	remaining: 1m 30s
300:	learn: 0.5346355	test: 0.5142959	best: 0.5245045 (67)	total: 33.8s	remaining: 1m 18s
400:	learn: 0.5357135	test: 0.5174037	best: 0.5245045 (67)	total: 44.2s	remaining: 1m 6s
500:	learn: 0.5372339	test: 0.5175759	best: 0.5245045 (67)	total: 55.1s	remaining: 54.9s
600:	learn: 0.5401888	test: 0.5164151	best: 0.5245045 (67)	total: 1m 7s	remaining: 44.5s
700:	learn: 0.5507263	test: 0.5163751	best: 0.5245045 (67)	total: 1m 21s	remaining: 34.8s
800:	learn: 0.5847809	test: 0.5372603	best: 0.5385845 (796)	total: 1m 40s	remaining: 24.9s
900:	learn: 0.6044289	test: 0.5422448	best: 0.5435738 (898)	total: 1m 57s	remaining: 12.9s
999:	learn: 0.6173242	test: 0.5481277	best: 0.5481277 (999)	total: 2m 15s	remaining: 0us

bestTest = 0.5481277484
bestIteration = 999

6:	loss: 0.5481277	best: 0.5729097 (5)	total: 16m 53s	remaining: 1h 19s
0:	learn: 0.5087635	test: 0.5108648	best: 0.5108648 (0)	total: 130ms	remaining: 2m 9s
100:	learn: 0.5321018	test: 0.5220640	best: 0.5566067 (4)	total: 10.1s	remaining: 1m 29s
200:	learn: 0.5354056	test: 0.5176095	best: 0.5566067 (4)	total: 20.5s	remaining: 1m 21s
300:	learn: 0.5340022	test: 0.5133330	best: 0.5566067 (4)	total: 31.7s	remaining: 1m 13s
400:	learn: 0.5353450	test: 0.5123352	best: 0.5566067 (4)	total: 42.6s	remaining: 1m 3s
500:	learn: 0.5701335	test: 0.5268055	best: 0.5566067 (4)	total: 57.6s	remaining: 57.4s
600:	learn: 0.6023605	test: 0.5394784	best: 0.5566067 (4)	total: 1m 16s	remaining: 50.5s
700:	learn: 0.6215944	test: 0.5489379	best: 0.5566067 (4)	total: 1m 33s	remaining: 40s
800:	learn: 0.6356176	test: 0.5568106	best: 0.5569037 (791)	total: 1m 51s	remaining: 27.6s
900:	learn: 0.6435393	test: 0.5600283	best: 0.5600283 (900)	total: 2m 9s	remaining: 14.3s
999:	learn: 0.6538457	test: 0.5645111	best: 0.5654061 (997)	total: 2m 27s	remaining: 0us

bestTest = 0.5654060756
bestIteration = 997

7:	loss: 0.5654061	best: 0.5729097 (5)	total: 19m 21s	remaining: 58m 3s
0:	learn: 0.5620988	test: 0.5596737	best: 0.5596737 (0)	total: 230ms	remaining: 3m 49s
100:	learn: 0.5456125	test: 0.5274289	best: 0.5596737 (0)	total: 13.5s	remaining: 1m 59s
200:	learn: 0.5492285	test: 0.5241379	best: 0.5596737 (0)	total: 26.6s	remaining: 1m 45s
300:	learn: 0.5489897	test: 0.5220784	best: 0.5596737 (0)	total: 38.5s	remaining: 1m 29s
400:	learn: 0.5505117	test: 0.5227828	best: 0.5596737 (0)	total: 51.2s	remaining: 1m 16s
500:	learn: 0.5533297	test: 0.5241447	best: 0.5596737 (0)	total: 1m 3s	remaining: 1m 3s
600:	learn: 0.5596388	test: 0.5247396	best: 0.5596737 (0)	total: 1m 17s	remaining: 51.7s
700:	learn: 0.5987255	test: 0.5400480	best: 0.5596737 (0)	total: 1m 38s	remaining: 42s
800:	learn: 0.6293765	test: 0.5562156	best: 0.5596737 (0)	total: 1m 59s	remaining: 29.8s
900:	learn: 0.6486893	test: 0.5646840	best: 0.5653657 (876)	total: 2m 20s	remaining: 15.5s
999:	learn: 0.6662100	test: 0.5742215	best: 0.5746556 (988)	total: 2m 42s	remaining: 0us

bestTest = 0.574655623
bestIteration = 988

8:	loss: 0.5746556	best: 0.5746556 (8)	total: 22m 3s	remaining: 56m 22s
0:	learn: 0.5620988	test: 0.5596737	best: 0.5596737 (0)	total: 191ms	remaining: 3m 10s
100:	learn: 0.5478361	test: 0.5236332	best: 0.5596737 (0)	total: 13.4s	remaining: 1m 59s
200:	learn: 0.5477591	test: 0.5187619	best: 0.5596737 (0)	total: 26.5s	remaining: 1m 45s
300:	learn: 0.5513672	test: 0.5210398	best: 0.5596737 (0)	total: 38.6s	remaining: 1m 29s
400:	learn: 0.5604506	test: 0.5221156	best: 0.5596737 (0)	total: 52s	remaining: 1m 17s
500:	learn: 0.6024072	test: 0.5381705	best: 0.5596737 (0)	total: 1m 12s	remaining: 1m 12s
600:	learn: 0.6384364	test: 0.5611956	best: 0.5625304 (597)	total: 1m 33s	remaining: 1m 1s
700:	learn: 0.6621284	test: 0.5729305	best: 0.5729305 (700)	total: 1m 55s	remaining: 49.1s
800:	learn: 0.6783582	test: 0.5822427	best: 0.5822427 (800)	total: 2m 16s	remaining: 33.9s
900:	learn: 0.6915088	test: 0.5865121	best: 0.5866548 (895)	total: 2m 36s	remaining: 17.2s
999:	learn: 0.7029895	test: 0.5923889	best: 0.5936352 (991)	total: 2m 58s	remaining: 0us

bestTest = 0.5936351967
bestIteration = 991

9:	loss: 0.5936352	best: 0.5936352 (9)	total: 25m 1s	remaining: 55m 3s
0:	learn: 0.5620988	test: 0.5596737	best: 0.5596737 (0)	total: 228ms	remaining: 3m 47s
100:	learn: 0.5488797	test: 0.5301562	best: 0.5596737 (0)	total: 13.4s	remaining: 1m 59s
200:	learn: 0.5491296	test: 0.5298176	best: 0.5596737 (0)	total: 25.8s	remaining: 1m 42s
300:	learn: 0.5482713	test: 0.5271674	best: 0.5596737 (0)	total: 38.3s	remaining: 1m 28s
400:	learn: 0.5523875	test: 0.5249113	best: 0.5596737 (0)	total: 50s	remaining: 1m 14s
500:	learn: 0.5542136	test: 0.5251377	best: 0.5596737 (0)	total: 1m 2s	remaining: 1m 2s
600:	learn: 0.5659411	test: 0.5294588	best: 0.5596737 (0)	total: 1m 17s	remaining: 51.4s
700:	learn: 0.5976016	test: 0.5420313	best: 0.5596737 (0)	total: 1m 37s	remaining: 41.8s
800:	learn: 0.6296771	test: 0.5607781	best: 0.5609295 (799)	total: 1m 58s	remaining: 29.5s
900:	learn: 0.6521802	test: 0.5682598	best: 0.5685878 (897)	total: 2m 20s	remaining: 15.4s
999:	learn: 0.6640859	test: 0.5699106	best: 0.5730798 (977)	total: 2m 42s	remaining: 0us

bestTest = 0.5730798076
bestIteration = 977

10:	loss: 0.5730798	best: 0.5936352 (9)	total: 27m 43s	remaining: 52m 55s
0:	learn: 0.5620988	test: 0.5596737	best: 0.5596737 (0)	total: 211ms	remaining: 3m 31s
100:	learn: 0.5404786	test: 0.5243034	best: 0.5596737 (0)	total: 12s	remaining: 1m 46s
200:	learn: 0.5413319	test: 0.5210629	best: 0.5596737 (0)	total: 23.9s	remaining: 1m 34s
300:	learn: 0.5426786	test: 0.5206612	best: 0.5596737 (0)	total: 35.5s	remaining: 1m 22s
400:	learn: 0.5580031	test: 0.5254252	best: 0.5596737 (0)	total: 51.6s	remaining: 1m 17s
500:	learn: 0.6071888	test: 0.5422072	best: 0.5596737 (0)	total: 1m 11s	remaining: 1m 11s
600:	learn: 0.6396474	test: 0.5589473	best: 0.5596737 (0)	total: 1m 33s	remaining: 1m 2s
700:	learn: 0.6602786	test: 0.5689113	best: 0.5702286 (690)	total: 1m 55s	remaining: 49.2s
800:	learn: 0.6777988	test: 0.5772056	best: 0.5796102 (792)	total: 2m 16s	remaining: 33.8s
900:	learn: 0.6907037	test: 0.5818440	best: 0.5839791 (872)	total: 2m 38s	remaining: 17.4s
999:	learn: 0.7033306	test: 0.5884437	best: 0.5898446 (996)	total: 3m	remaining: 0us

bestTest = 0.5898446146
bestIteration = 996

11:	loss: 0.5898446	best: 0.5936352 (9)	total: 30m 43s	remaining: 51m 13s
0:	learn: 0.5087635	test: 0.5108648	best: 0.5108648 (0)	total: 83.9ms	remaining: 1m 23s
100:	learn: 0.5335362	test: 0.5212636	best: 0.5680543 (2)	total: 12.6s	remaining: 1m 52s
200:	learn: 0.5319516	test: 0.5211448	best: 0.5680543 (2)	total: 23.3s	remaining: 1m 32s
300:	learn: 0.5342422	test: 0.5187055	best: 0.5680543 (2)	total: 33.5s	remaining: 1m 17s
400:	learn: 0.5356996	test: 0.5183576	best: 0.5680543 (2)	total: 44.4s	remaining: 1m 6s
500:	learn: 0.5351212	test: 0.5166436	best: 0.5680543 (2)	total: 55.4s	remaining: 55.2s
600:	learn: 0.5437038	test: 0.5214656	best: 0.5680543 (2)	total: 1m 8s	remaining: 45.2s
700:	learn: 0.5687221	test: 0.5326825	best: 0.5680543 (2)	total: 1m 25s	remaining: 36.4s
800:	learn: 0.6106570	test: 0.5506365	best: 0.5680543 (2)	total: 1m 47s	remaining: 26.7s
900:	learn: 0.6373115	test: 0.5588313	best: 0.5680543 (2)	total: 2m 9s	remaining: 14.2s
999:	learn: 0.6528531	test: 0.5701890	best: 0.5701890 (999)	total: 2m 30s	remaining: 0us

bestTest = 0.5701890301
bestIteration = 999

12:	loss: 0.5701890	best: 0.5936352 (9)	total: 33m 14s	remaining: 48m 34s
0:	learn: 0.5087635	test: 0.5108648	best: 0.5108648 (0)	total: 138ms	remaining: 2m 18s
100:	learn: 0.5369424	test: 0.5272329	best: 0.5680543 (2)	total: 11.9s	remaining: 1m 45s
200:	learn: 0.5365065	test: 0.5207440	best: 0.5680543 (2)	total: 23.6s	remaining: 1m 33s
300:	learn: 0.5370261	test: 0.5193011	best: 0.5680543 (2)	total: 35s	remaining: 1m 21s
400:	learn: 0.5409707	test: 0.5179650	best: 0.5680543 (2)	total: 48s	remaining: 1m 11s
500:	learn: 0.5894263	test: 0.5380978	best: 0.5680543 (2)	total: 1m 7s	remaining: 1m 7s
600:	learn: 0.6327816	test: 0.5571048	best: 0.5680543 (2)	total: 1m 28s	remaining: 58.8s
700:	learn: 0.6554754	test: 0.5678913	best: 0.5680543 (2)	total: 1m 50s	remaining: 47.2s
800:	learn: 0.6737891	test: 0.5743306	best: 0.5746932 (792)	total: 2m 12s	remaining: 33s
900:	learn: 0.6889769	test: 0.5810215	best: 0.5810215 (900)	total: 2m 33s	remaining: 16.9s
999:	learn: 0.7001177	test: 0.5861885	best: 0.5861885 (999)	total: 2m 54s	remaining: 0us

bestTest = 0.5861884845
bestIteration = 999

13:	loss: 0.5861885	best: 0.5936352 (9)	total: 36m 9s	remaining: 46m 28s
0:	learn: 0.5087635	test: 0.5108648	best: 0.5108648 (0)	total: 75.5ms	remaining: 1m 15s
100:	learn: 0.5426894	test: 0.5195853	best: 0.5299676 (28)	total: 13.1s	remaining: 1m 56s
200:	learn: 0.5371711	test: 0.5184823	best: 0.5299676 (28)	total: 24.7s	remaining: 1m 38s
300:	learn: 0.5392819	test: 0.5198199	best: 0.5299676 (28)	total: 36.1s	remaining: 1m 23s
400:	learn: 0.5419283	test: 0.5167996	best: 0.5299676 (28)	total: 47.6s	remaining: 1m 11s
500:	learn: 0.5420967	test: 0.5162847	best: 0.5299676 (28)	total: 59.1s	remaining: 58.9s
600:	learn: 0.5498168	test: 0.5220769	best: 0.5299676 (28)	total: 1m 11s	remaining: 47.6s
700:	learn: 0.5755352	test: 0.5280043	best: 0.5299676 (28)	total: 1m 29s	remaining: 38s
800:	learn: 0.6178136	test: 0.5515343	best: 0.5521706 (799)	total: 1m 51s	remaining: 27.6s
900:	learn: 0.6396262	test: 0.5607892	best: 0.5614394 (893)	total: 2m 12s	remaining: 14.5s
999:	learn: 0.6562299	test: 0.5678990	best: 0.5686606 (986)	total: 2m 33s	remaining: 0us

bestTest = 0.5686605635
bestIteration = 986

14:	loss: 0.5686606	best: 0.5936352 (9)	total: 38m 42s	remaining: 43m 52s
0:	learn: 0.5087635	test: 0.5108648	best: 0.5108648 (0)	total: 74.4ms	remaining: 1m 14s
100:	learn: 0.5318066	test: 0.5153097	best: 0.5566067 (4)	total: 12.3s	remaining: 1m 49s
200:	learn: 0.5352157	test: 0.5116279	best: 0.5566067 (4)	total: 24.6s	remaining: 1m 37s
300:	learn: 0.5397780	test: 0.5118047	best: 0.5566067 (4)	total: 35.7s	remaining: 1m 23s
400:	learn: 0.5419027	test: 0.5118382	best: 0.5566067 (4)	total: 46.9s	remaining: 1m 10s
500:	learn: 0.5915901	test: 0.5388998	best: 0.5566067 (4)	total: 1m 5s	remaining: 1m 5s
600:	learn: 0.6307264	test: 0.5570732	best: 0.5595364 (595)	total: 1m 27s	remaining: 57.9s
700:	learn: 0.6552184	test: 0.5696348	best: 0.5722357 (682)	total: 1m 48s	remaining: 46.4s
800:	learn: 0.6715327	test: 0.5751733	best: 0.5765590 (756)	total: 2m 9s	remaining: 32.1s
900:	learn: 0.6865008	test: 0.5813005	best: 0.5815376 (892)	total: 2m 30s	remaining: 16.6s
999:	learn: 0.6994801	test: 0.5904206	best: 0.5904206 (999)	total: 2m 52s	remaining: 0us

bestTest = 0.5904205917
bestIteration = 999

15:	loss: 0.5904206	best: 0.5936352 (9)	total: 41m 34s	remaining: 41m 34s
0:	learn: 0.5620988	test: 0.5596737	best: 0.5596737 (0)	total: 152ms	remaining: 2m 31s
100:	learn: 0.5399076	test: 0.5206881	best: 0.5596737 (0)	total: 12.7s	remaining: 1m 52s
200:	learn: 0.5422477	test: 0.5196578	best: 0.5596737 (0)	total: 24.1s	remaining: 1m 35s
300:	learn: 0.5397453	test: 0.5156173	best: 0.5596737 (0)	total: 34.7s	remaining: 1m 20s
400:	learn: 0.5418178	test: 0.5166644	best: 0.5596737 (0)	total: 45.8s	remaining: 1m 8s
500:	learn: 0.5430517	test: 0.5173946	best: 0.5596737 (0)	total: 57.1s	remaining: 56.9s
600:	learn: 0.5490615	test: 0.5205247	best: 0.5596737 (0)	total: 1m 9s	remaining: 46s
700:	learn: 0.5717395	test: 0.5282968	best: 0.5596737 (0)	total: 1m 25s	remaining: 36.6s
800:	learn: 0.5955064	test: 0.5404229	best: 0.5596737 (0)	total: 1m 44s	remaining: 25.9s
900:	learn: 0.6102779	test: 0.5453175	best: 0.5596737 (0)	total: 2m 1s	remaining: 13.3s
999:	learn: 0.6226781	test: 0.5509109	best: 0.5596737 (0)	total: 2m 19s	remaining: 0us

bestTest = 0.5596737151
bestIteration = 0

16:	loss: 0.5596737	best: 0.5936352 (9)	total: 43m 54s	remaining: 38m 44s
0:	learn: 0.5620988	test: 0.5596737	best: 0.5596737 (0)	total: 261ms	remaining: 4m 21s
100:	learn: 0.5303844	test: 0.5128321	best: 0.5596737 (0)	total: 10.7s	remaining: 1m 35s
200:	learn: 0.5310928	test: 0.5067234	best: 0.5596737 (0)	total: 22.3s	remaining: 1m 28s
300:	learn: 0.5339608	test: 0.5083948	best: 0.5596737 (0)	total: 33.5s	remaining: 1m 17s
400:	learn: 0.5418875	test: 0.5151338	best: 0.5596737 (0)	total: 46.3s	remaining: 1m 9s
500:	learn: 0.5791465	test: 0.5315034	best: 0.5596737 (0)	total: 1m 4s	remaining: 1m 3s
600:	learn: 0.6063014	test: 0.5465220	best: 0.5596737 (0)	total: 1m 21s	remaining: 54.2s
700:	learn: 0.6275468	test: 0.5542575	best: 0.5596737 (0)	total: 1m 38s	remaining: 42.2s
800:	learn: 0.6417767	test: 0.5618177	best: 0.5622811 (796)	total: 1m 57s	remaining: 29.1s
900:	learn: 0.6498802	test: 0.5662726	best: 0.5671151 (873)	total: 2m 14s	remaining: 14.8s
999:	learn: 0.6586402	test: 0.5707176	best: 0.5709839 (994)	total: 2m 32s	remaining: 0us

bestTest = 0.5709839491
bestIteration = 994

17:	loss: 0.5709839	best: 0.5936352 (9)	total: 46m 27s	remaining: 36m 8s
0:	learn: 0.5620988	test: 0.5596737	best: 0.5596737 (0)	total: 292ms	remaining: 4m 52s
100:	learn: 0.5349881	test: 0.5182379	best: 0.5601108 (1)	total: 10.8s	remaining: 1m 36s
200:	learn: 0.5357127	test: 0.5176648	best: 0.5601108 (1)	total: 22.1s	remaining: 1m 27s

In [43]:
best_model = CatBoostClassifier(
    **grid_result['params'],
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=100,
    cat_features=cat_features
)

best_model.fit(
    x_train_over,
    y_train_over
)

0:	learn: 0.5626027	total: 171ms	remaining: 2m 50s
100:	learn: 0.5375732	total: 15.3s	remaining: 2m 15s
200:	learn: 0.5439852	total: 28.6s	remaining: 1m 53s
300:	learn: 0.5481991	total: 42.7s	remaining: 1m 39s
400:	learn: 0.5550801	total: 58.5s	remaining: 1m 27s
500:	learn: 0.5968225	total: 1m 19s	remaining: 1m 19s
600:	learn: 0.6327821	total: 1m 43s	remaining: 1m 8s
700:	learn: 0.6561435	total: 2m 6s	remaining: 53.9s
800:	learn: 0.6729402	total: 2m 29s	remaining: 37.2s
900:	learn: 0.6860879	total: 2m 53s	remaining: 19s
999:	learn: 0.6961180	total: 3m 14s	remaining: 0us

CatBoostClassifier(bagging_temperature=1, cat_features=['gender', 'sleep_quality', 'alcohol_consumption', 'smoking_level', 'diet_type', 'exercise_type', 'device_usage', 'caffeine_intake'], depth=6, eval_metric='F1', iterations=1000, l2_leaf_reg=10, learning_rate=0.03, loss_function='Logloss', random_state=42, random_strength=5, verbose=100)

Tes Data

In [44]:
# Prediksi langsung
y_pred = cat_model.predict(x_test)

# Evaluasi
print(classification_report(y_test, y_pred))

cat_acc = accuracy_score(y_test, y_pred)

print("Akurasi CatBoost = {:.2f}%".format(cat_acc*100))

              precision    recall  f1-score   support

           0       0.70      0.59      0.64     14019
           1       0.30      0.42      0.35      5981

    accuracy                           0.54     20000
   macro avg       0.50      0.50      0.50     20000
weighted avg       0.58      0.54      0.56     20000

Akurasi CatBoost = 53.92%